### ISSUE TITLE
Feature Request : suggest random password

### ISSUE THREAD

**Issue by Sn4kY** [Akiletour/aki-vault#5]
Hi dude
Do you think that is a good idead to add a button to suggest a random password to encrypt for quick create and sharing secured password ?
of course, should be generated by browser, with a JS function.
XOXO

**Comment by Akiletour** [comment]
Hej !

good idea, any suggestion @Sn4kY about the length of the suggested password ? maybe 12/16 ? 

The front already use a password generation for the private decryption key, we can use this function to generate a random password and automatically fill the textarea.

I'll just need to figure out how i can visually implement this on the design system

Cheers :)

**Comment by Sn4kY** [comment]
About the password, a configurable length in .env.local seems to be perfect. 12 by default should be enough
